import type {
   TimelineRowType,
   TimelineTask,
} from '../types/timeline.types';

export const sampleRows: TimelineRowType[] = [
   {
      id: 'row-1',
      label: 'Frontend Team',
      avatar: '/avatars/frontend.png',
      tasks: ['task-1', 'task-2', 'task-9'],
   },
   {
      id: 'row-2',
      label: 'Backend Team',
      avatar: '/avatars/backend.png',
      tasks: ['task-3', 'task-10'],
   },
   {
      id: 'row-3',
      label: 'Design Team',
      avatar: '/avatars/design.png',
      tasks: ['task-4', 'task-11'],
   },
   {
      id: 'row-4',
      label: 'QA Team',
      avatar: '/avatars/qa.png',
      tasks: ['task-5', 'task-12'],
   },
   {
      id: 'row-5',
      label: 'Product Team',
      avatar: '/avatars/product.png',
      tasks: ['task-6'],
   },
   {
      id: 'row-6',
      label: 'Marketing Team',
      avatar: '/avatars/marketing.png',
      tasks: ['task-7', 'task-8'],
   },
];

export const sampleTasks: Record<string, TimelineTask> = {
   // ---- Frontend ----
   'task-1': {
      id: 'task-1',
      title: 'UI Component Development',
      startDate: new Date(2025, 9, 1),
      endDate: new Date(2025, 9, 31),
      progress: 60,
      assignee: 'Frontend Team',
      rowId: 'row-1',
      dependencies: [],
      color: '#3b82f6',
      isMilestone: false,
   },
   'task-2': {
      id: 'task-2',
      title: 'Integration Testing',
      startDate: new Date(2025, 8, 20),
      endDate: new Date(2025, 8, 30),
      progress: 100,
      assignee: 'Frontend Team',
      rowId: 'row-1',
      dependencies: ['task-1', 'task-3'],
      color: '#3b82f6',
      isMilestone: false,
   },
   'task-9': {
      id: 'task-9',
      title: 'Responsive Layout Fixes',
      startDate: new Date(2025, 9, 18),
      endDate: new Date(2025, 9, 25),
      progress: 40,
      assignee: 'Frontend Team',
      rowId: 'row-1',
      dependencies: ['task-2'],
      color: '#3b82f6',
      isMilestone: false,
   },

   // ---- Backend ----
   'task-3': {
      id: 'task-3',
      title: 'API Development',
      startDate: new Date(2025, 9, 1),
      endDate: new Date(2025, 9, 14),
      progress: 80,
      assignee: 'Backend Team',
      rowId: 'row-2',
      dependencies: [],
      color: '#10b981',
      isMilestone: false,
   },
   'task-10': {
      id: 'task-10',
      title: 'Database Optimization',
      startDate: new Date(2025, 9, 16),
      endDate: new Date(2025, 9, 28),
      progress: 30,
      assignee: 'Backend Team',
      rowId: 'row-2',
      dependencies: ['task-3'],
      color: '#10b981',
      isMilestone: false,
   },

   // ---- Design ----
   'task-4': {
      id: 'task-4',
      title: 'Design System Update',
      startDate: new Date(2025, 9, 5),
      endDate: new Date(2025, 9, 20),
      progress: 100,
      assignee: 'Design Team',
      rowId: 'row-3',
      dependencies: [],
      color: '#f59e0b',
      isMilestone: false,
   },
   'task-11': {
      id: 'task-11',
      title: 'UX Audit & Feedback',
      startDate: new Date(2025, 9, 21),
      endDate: new Date(2025, 9, 27),
      progress: 50,
      assignee: 'Design Team',
      rowId: 'row-3',
      dependencies: ['task-4'],
      color: '#f59e0b',
      isMilestone: false,
   },

   // ---- QA ----
   'task-5': {
      id: 'task-5',
      title: 'Regression Testing',
      startDate: new Date(2025, 9, 10),
      endDate: new Date(2025, 9, 18),
      progress: 70,
      assignee: 'QA Team',
      rowId: 'row-4',
      dependencies: ['task-2', 'task-3'],
      color: '#ec4899',
      isMilestone: false,
   },
   'task-12': {
      id: 'task-12',
      title: 'Performance Benchmarking',
      startDate: new Date(2025, 9, 19),
      endDate: new Date(2025, 9, 28),
      progress: 20,
      assignee: 'QA Team',
      rowId: 'row-4',
      dependencies: ['task-5'],
      color: '#ec4899',
      isMilestone: false,
   },

   // ---- Product ----
   'task-6': {
      id: 'task-6',
      title: 'Roadmap Planning Q4',
      startDate: new Date(2025, 8, 25),
      endDate: new Date(2025, 9, 10),
      progress: 90,
      assignee: 'Product Team',
      rowId: 'row-5',
      dependencies: [],
      color: '#8b5cf6',
      isMilestone: false,
   },

   // ---- Marketing ----
   'task-7': {
      id: 'task-7',
      title: 'Campaign Content Creation',
      startDate: new Date(2025, 9, 3),
      endDate: new Date(2025, 9, 15),
      progress: 55,
      assignee: 'Marketing Team',
      rowId: 'row-6',
      dependencies: [],
      color: '#ef4444',
      isMilestone: false,
   },
   'task-8': {
      id: 'task-8',
      title: 'Ad Launch Preparation',
      startDate: new Date(2025, 9, 16),
      endDate: new Date(2025, 9, 25),
      progress: 10,
      assignee: 'Marketing Team',
      rowId: 'row-6',
      dependencies: ['task-7'],
      color: '#ef4444',
      isMilestone: false,
   },
};

export const sampleBigRows: TimelineRowType[] = [
   {
      id: 'row-1',
      label: 'Frontend Team',
      avatar: '/avatars/frontend.png',
      tasks: ['task-1', 'task-2', 'task-9', 'task-13', 'task-14', 'task-15'],
   },
   {
      id: 'row-2',
      label: 'Backend Team',
      avatar: '/avatars/backend.png',
      tasks: ['task-3', 'task-10', 'task-16', 'task-17', 'task-18'],
   },
   {
      id: 'row-3',
      label: 'Design Team',
      avatar: '/avatars/design.png',
      tasks: ['task-4', 'task-11', 'task-19', 'task-20', 'task-21'],
   },
   {
      id: 'row-4',
      label: 'QA Team',
      avatar: '/avatars/qa.png',
      tasks: ['task-5', 'task-12', 'task-22', 'task-23', 'task-24'],
   },
   {
      id: 'row-5',
      label: 'Product Team',
      avatar: '/avatars/product.png',
      tasks: ['task-6', 'task-25', 'task-26', 'task-27'],
   },
   {
      id: 'row-6',
      label: 'Marketing Team',
      avatar: '/avatars/marketing.png',
      tasks: ['task-7', 'task-8', 'task-28', 'task-29', 'task-30'],
   },
];

export const sampleBigTasks: Record<string, TimelineTask> = {
   // ---- Frontend ----
   'task-1': {
      id: 'task-1',
      title: 'UI Component Development',
      startDate: new Date(2025, 9, 1),
      endDate: new Date(2025, 9, 15),
      progress: 60,
      assignee: 'Frontend Team',
      rowId: 'row-1',
      dependencies: [],
      color: '#3b82f6',
      isMilestone: false,
   },
   'task-2': {
      id: 'task-2',
      title: 'Integration Testing',
      startDate: new Date(2025, 8, 20),
      endDate: new Date(2025, 8, 30),
      progress: 100,
      assignee: 'Frontend Team',
      rowId: 'row-1',
      dependencies: ['task-1', 'task-3'],
      color: '#3b82f6',
      isMilestone: false,
   },
   'task-9': {
      id: 'task-9',
      title: 'Responsive Layout Fixes',
      startDate: new Date(2025, 9, 18),
      endDate: new Date(2025, 9, 25),
      progress: 40,
      assignee: 'Frontend Team',
      rowId: 'row-1',
      dependencies: ['task-2'],
      color: '#3b82f6',
      isMilestone: false,
   },
   'task-13': {
      id: 'task-13',
      title: 'Refactor State Management',
      startDate: new Date(2025, 9, 26),
      endDate: new Date(2025, 10, 5),
      progress: 15,
      assignee: 'Frontend Team',
      rowId: 'row-1',
      dependencies: ['task-9'],
      color: '#3b82f6',
      isMilestone: false,
   },
   'task-14': {
      id: 'task-14',
      title: 'Implement User Auth Flow',
      startDate: new Date(2025, 9, 28),
      endDate: new Date(2025, 10, 10),
      progress: 0,
      assignee: 'Frontend Team',
      rowId: 'row-1',
      dependencies: ['task-16'],
      color: '#3b82f6',
      isMilestone: false,
   },
   'task-15': {
      id: 'task-15',
      title: 'v1.0 Release Milestone',
      startDate: new Date(2025, 10, 15),
      endDate: new Date(2025, 10, 15),
      progress: 0,
      assignee: 'Frontend Team',
      rowId: 'row-1',
      dependencies: ['task-13', 'task-14', 'task-18', 'task-24'],
      color: '#3b82f6',
      isMilestone: true,
   },

   // ---- Backend ----
   'task-3': {
      id: 'task-3',
      title: 'API Development',
      startDate: new Date(2025, 9, 1),
      endDate: new Date(2025, 9, 14),
      progress: 80,
      assignee: 'Backend Team',
      rowId: 'row-2',
      dependencies: [],
      color: '#10b981',
      isMilestone: false,
   },
   'task-10': {
      id: 'task-10',
      title: 'Database Optimization',
      startDate: new Date(2025, 9, 16),
      endDate: new Date(2025, 9, 28),
      progress: 30,
      assignee: 'Backend Team',
      rowId: 'row-2',
      dependencies: ['task-3'],
      color: '#10b981',
      isMilestone: false,
   },
   'task-16': {
      id: 'task-16',
      title: 'Setup Authentication Service',
      startDate: new Date(2025, 9, 25),
      endDate: new Date(2025, 10, 3),
      progress: 20,
      assignee: 'Backend Team',
      rowId: 'row-2',
      dependencies: ['task-10'],
      color: '#10b981',
      isMilestone: false,
   },
   'task-17': {
      id: 'task-17',
      title: 'Implement Caching Layer',
      startDate: new Date(2025, 9, 29),
      endDate: new Date(2025, 10, 7),
      progress: 0,
      assignee: 'Backend Team',
      rowId: 'row-2',
      dependencies: [],
      color: '#10b981',
      isMilestone: false,
   },
   'task-18': {
      id: 'task-18',
      title: 'Deploy to Staging',
      startDate: new Date(2025, 10, 8),
      endDate: new Date(2025, 10, 12),
      progress: 0,
      assignee: 'Backend Team',
      rowId: 'row-2',
      dependencies: ['task-16', 'task-17'],
      color: '#10b981',
      isMilestone: false,
   },

   // ---- Design ----
   'task-4': {
      id: 'task-4',
      title: 'Design System Update',
      startDate: new Date(2025, 9, 5),
      endDate: new Date(2025, 9, 20),
      progress: 100,
      assignee: 'Design Team',
      rowId: 'row-3',
      dependencies: [],
      color: '#f59e0b',
      isMilestone: false,
   },
   'task-11': {
      id: 'task-11',
      title: 'UX Audit & Feedback',
      startDate: new Date(2025, 9, 21),
      endDate: new Date(2025, 9, 27),
      progress: 50,
      assignee: 'Design Team',
      rowId: 'row-3',
      dependencies: ['task-4'],
      color: '#f59e0b',
      isMilestone: false,
   },
   'task-19': {
      id: 'task-19',
      title: 'Mobile View Mockups',
      startDate: new Date(2025, 9, 28),
      endDate: new Date(2025, 10, 6),
      progress: 10,
      assignee: 'Design Team',
      rowId: 'row-3',
      dependencies: ['task-11'],
      color: '#f59e0b',
      isMilestone: false,
   },
   'task-20': {
      id: 'task-20',
      title: 'Accessibility Review',
      startDate: new Date(2025, 10, 1),
      endDate: new Date(2025, 10, 8),
      progress: 0,
      assignee: 'Design Team',
      rowId: 'row-3',
      dependencies: [],
      color: '#f59e0b',
      isMilestone: false,
   },
   'task-21': {
      id: 'task-21',
      title: 'Finalize Design Specs',
      startDate: new Date(2025, 10, 7),
      endDate: new Date(2025, 10, 14),
      progress: 0,
      assignee: 'Design Team',
      rowId: 'row-3',
      dependencies: ['task-19', 'task-20'],
      color: '#f59e0b',
      isMilestone: false,
   },

   // ---- QA ----
   'task-5': {
      id: 'task-5',
      title: 'Regression Testing',
      startDate: new Date(2025, 9, 10),
      endDate: new Date(2025, 9, 18),
      progress: 70,
      assignee: 'QA Team',
      rowId: 'row-4',
      dependencies: ['task-2', 'task-3'],
      color: '#ec4899',
      isMilestone: false,
   },
   'task-12': {
      id: 'task-12',
      title: 'Performance Benchmarking',
      startDate: new Date(2025, 9, 19),
      endDate: new Date(2025, 9, 28),
      progress: 20,
      assignee: 'QA Team',
      rowId: 'row-4',
      dependencies: ['task-5'],
      color: '#ec4899',
      isMilestone: false,
   },
   'task-22': {
      id: 'task-22',
      title: 'Write E2E Test Cases',
      startDate: new Date(2025, 9, 29),
      endDate: new Date(2025, 10, 5),
      progress: 0,
      assignee: 'QA Team',
      rowId: 'row-4',
      dependencies: ['task-12'],
      color: '#ec4899',
      isMilestone: false,
   },
   'task-23': {
      id: 'task-23',
      title: 'Security & Penetration Testing',
      startDate: new Date(2025, 10, 4),
      endDate: new Date(2025, 10, 11),
      progress: 0,
      assignee: 'QA Team',
      rowId: 'row-4',
      dependencies: ['task-16'],
      color: '#ec4899',
      isMilestone: false,
   },
   'task-24': {
      id: 'task-24',
      title: 'UAT Support',
      startDate: new Date(2025, 10, 6),
      endDate: new Date(2025, 10, 14),
      progress: 0,
      assignee: 'QA Team',
      rowId: 'row-4',
      dependencies: ['task-22', 'task-23'],
      color: '#ec4899',
      isMilestone: false,
   },

   // ---- Product ----
   'task-6': {
      id: 'task-6',
      title: 'Roadmap Planning Q4',
      startDate: new Date(2025, 8, 25),
      endDate: new Date(2025, 9, 10),
      progress: 90,
      assignee: 'Product Team',
      rowId: 'row-5',
      dependencies: [],
      color: '#8b5cf6',
      isMilestone: false,
   },
   'task-25': {
      id: 'task-25',
      title: 'Gather User Feedback',
      startDate: new Date(2025, 9, 15),
      endDate: new Date(2025, 9, 30),
      progress: 75,
      assignee: 'Product Team',
      rowId: 'row-5',
      dependencies: ['task-6'],
      color: '#8b5cf6',
      isMilestone: false,
   },
   'task-26': {
      id: 'task-26',
      title: 'Define Q1 2026 Epics',
      startDate: new Date(2025, 10, 1),
      endDate: new Date(2025, 10, 15),
      progress: 0,
      assignee: 'Product Team',
      rowId: 'row-5',
      dependencies: [],
      color: '#8b5cf6',
      isMilestone: false,
   },
   'task-27': {
      id: 'task-27',
      title: 'Prioritize Backlog',
      startDate: new Date(2025, 10, 5),
      endDate: new Date(2025, 10, 18),
      progress: 0,
      assignee: 'Product Team',
      rowId: 'row-5',
      dependencies: ['task-25', 'task-26'],
      color: '#8b5cf6',
      isMilestone: false,
   },

   // ---- Marketing ----
   'task-7': {
      id: 'task-7',
      title: 'Campaign Content Creation',
      startDate: new Date(2025, 9, 3),
      endDate: new Date(2025, 9, 15),
      progress: 55,
      assignee: 'Marketing Team',
      rowId: 'row-6',
      dependencies: [],
      color: '#ef4444',
      isMilestone: false,
   },
   'task-8': {
      id: 'task-8',
      title: 'Ad Launch Preparation',
      startDate: new Date(2025, 9, 16),
      endDate: new Date(2025, 9, 25),
      progress: 10,
      assignee: 'Marketing Team',
      rowId: 'row-6',
      dependencies: ['task-7'],
      color: '#ef4444',
      isMilestone: false,
   },
   'task-28': {
      id: 'task-28',
      title: 'Finalize Ad Copy',
      startDate: new Date(2025, 9, 26),
      endDate: new Date(2025, 10, 2),
      progress: 0,
      assignee: 'Marketing Team',
      rowId: 'row-6',
      dependencies: ['task-8'],
      color: '#ef4444',
      isMilestone: false,
   },
   'task-29': {
      id: 'task-29',
      title: 'Launch Social Media Campaign',
      startDate: new Date(2025, 10, 3),
      endDate: new Date(2025, 10, 17),
      progress: 0,
      assignee: 'Marketing Team',
      rowId: 'row-6',
      dependencies: ['task-28'],
      color: '#ef4444',
      isMilestone: false,
   },
   'task-30': {
      id: 'task-30',
      title: 'Analyze Campaign Metrics',
      startDate: new Date(2025, 10, 18),
      endDate: new Date(2025, 10, 25),
      progress: 0,
      assignee: 'Marketing Team',
      rowId: 'row-6',
      dependencies: ['task-29'],
      color: '#ef4444',
      isMilestone: false,
   },
};
